### ISSUE TITLE
Change of behavior on timeout in try-except blocks.

### ISSUE THREAD

**Issue by NnWn** [pytest-dev/pytest-timeout#93] opened 2021-07-08 05:33 UTC
For the same test as follow:
```
@pytest.mark.timeout(3)
def test_timeout():
    try:
        time.sleep(5)
    except Exception:
        print("An exception")
```
In pytest-timeout V1.2.1, the test would pass at around 3 seconds(which should actually fail since the sleep time is over 3 seconds) without throwing any error/warning: 

> test_dummy.py::test_timeout PASSED
> ==== 1 passed in 3.03 seconds ====

But in pytest-timeout V1.4.2, the test would fail around 3 seconds(which intuitively seems like should fail because sleep time is over 3 seconds), which is different with V1.2.1:

> test_dummy.py::test_timeout FAILED
> ==== 1 failed in 3.11 seconds ====

If you fixed something between V1.4.2 and V1.2.1, if this change of behavior is what you expected, could you please document it in the README? 
If I ignored something, please feel free to point out.
Thanks!

**Comment by The-Compiler** [comment] 2021-07-08 07:46
I can't reproduce - with 1.2.1:

```
============================= test session starts ==============================
platform linux -- Python 3.9.5, pytest-6.2.4, py-1.10.0, pluggy-0.13.1
rootdir: /home/florian/tmp/pytest-timeout, configfile: tox.ini
plugins: timeout-1.2.1
collected 1 item                                                               

x.py F                                                                   [100%]

=================================== FAILURES ===================================
_________________________________ test_timeout _________________________________

    @pytest.mark.timeout(3)
    def test_timeout():
        try:
>           time.sleep(5)
E           Failed: Timeout >3.0s

x.py:6: Failed
=========================== short test summary info ============================
FAILED x.py::test_timeout - Failed: Timeout >3.0s
============================== 1 failed in 3.02s ===============================
```

**Comment by NnWn** [comment] 2021-07-08 16:09
@The-Compiler Sorry about the confusion, the plugins I'm using are:
```
=========================== test session starts =============================
platform linux2 -- Python 2.7.15+, pytest-3.0.7, py-1.9.0, pluggy-0.4.0
rootdir: /home/xxxxx
plugins: timeout-1.2.1
```

**Comment by The-Compiler** [comment] 2021-07-08 16:23
Seems to have something to do with the older pytest version then. No idea what, though.

**Comment by NnWn** [comment] 2021-07-08 16:46
@The-Compiler Thanks Florian, so pytest-timeout itself didn't modify this try-except block timeout behavior directly through v1.2.1 to v1.4.2 right?

**Comment by The-Compiler** [comment] 2021-07-08 17:36
No idea on the details - I originally wanted to bisect this to find out where a change was introduced, but it looks like what you're running there is so old that it can't really be bisected without switching around both pytest and plugin versions.

**Comment by flub** [comment] 2021-07-18 19:30
Going to close this as "old pytest version".  Thanks @The-Compiler for the investigation, I'm afraid this isn't really worth investigating for me as it seems things currently work fine, so whether they did or did not in the past :shrug:

**Closed by flub** 2021-07-18 19:30 UTC
