### ISSUE TITLE
'pytest-timeout' does not stop any test anymore after updating from Python 3.8 to Python 3.10

### ISSUE THREAD

**Issue by AIGeneratedUsername** [pytest-dev/pytest-timeout#113] opened 2021-12-08 16:42 UTC
# Problem

See issue title. 

'pytest-timeout' always worked fine, but now, with Python 3.10.1, some tests may run forever until I manually cancel a whole tests session.

# Versions
- Python 3.10.1
- Pytest 6.2.5
- pytest-timeout 2.0.1
- pytest-asyncio 0.16.0
- Operation system: Lubuntu 20.04

# Logs
```python
ERROR    asyncio:base_events.py:1729 Exception in callback <TaskStepMethWrapper object at 0x7f590bbeaee0>()
handle: <Handle <TaskStepMethWrapper object at 0x7f590bbeaee0>() created at /usr/local/lib/python3.10/asyncio/events.py:80>
source_traceback: Object created at (most recent call last):
  File "project/venv/lib/python3.10/site-packages/pluggy/_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "project/venv/lib/python3.10/site-packages/pluggy/_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "project/venv/lib/python3.10/site-packages/_pytest/python.py", line 183, in pytest_pyfunc_call
    result = testfunction(**testargs)
  File "project/venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py", line 195, in inner
    _loop.run_until_complete(task)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 595, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1873, in _run_once
    handle._run()
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 748, in call_soon
    self._check_callback(callback, 'call_soon')
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 755, in _check_callback
    if (coroutines.iscoroutine(callback) or
  File "/usr/local/lib/python3.10/asyncio/coroutines.py", line 182, in iscoroutine
    if isinstance(obj, _COROUTINE_TYPES):
  File "/usr/local/lib/python3.10/abc.py", line 117, in __instancecheck__
    def __instancecheck__(cls, instance):
  File "project/venv/lib/python3.10/site-packages/pytest_timeout.py", line 207, in handler
    timeout_sigalrm(item, params.timeout)
  File "project/venv/lib/python3.10/site-packages/pytest_timeout.py", line 382, in timeout_sigalrm
    pytest.fail("Timeout >%ss" % timeout)
  File "project/venv/lib/python3.10/site-packages/_pytest/outcomes.py", line 153, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Timeout >60.0s
```

# Traceback 

Note: this traceback appears only when I cancel a tests session manually. Otherwise some test may run forever without any progress.

```python
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++

# [path to my test here, not important]

coro = <coroutine object my_test at 0x7f9c4e2fe0f0>
task = <Task pending name='Task-6227' coro=<my_test() running at /project...ted at /usr/local/lib/python3.10/asyncio/base_events.py:424> created at /usr/local/lib/python3.10/asyncio/tasks.py:634>

    @functools.wraps(func)
    def inner(**kwargs):
        coro = func(**kwargs)
        if coro is not None:
            task = asyncio.ensure_future(coro, loop=_loop)
            try:
>               _loop.run_until_complete(task)

../venv/lib/python3.10/site-packages/pytest_asyncio/plugin.py:195: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.10/asyncio/base_events.py:628: in run_until_complete
    self.run_forever()
/usr/local/lib/python3.10/asyncio/base_events.py:595: in run_forever
    self._run_once()
/usr/local/lib/python3.10/asyncio/base_events.py:1845: in _run_once
    event_list = self._selector.select(timeout)
/usr/local/lib/python3.10/selectors.py:469: in select
    fd_event_list = self._selector.poll(timeout, max_ev)
../venv/lib/python3.10/site-packages/pyppeteer/launcher.py:153: in _close_process
    self._loop.run_until_complete(self.killChrome())
/usr/local/lib/python3.10/asyncio/base_events.py:617: in run_until_complete
    self._check_running()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <_UnixSelectorEventLoop running=False closed=False debug=True>

    def _check_running(self):
        if self.is_running():
>           raise RuntimeError('This event loop is already running')
E           RuntimeError: This event loop is already running

/usr/local/lib/python3.10/asyncio/base_events.py:577: RuntimeError
```

**Comment by AIGeneratedUsername** [comment] 2021-12-09 08:18
I've found that my test hangs forever because 'pyppeteer' has a bug on Python 3.10. See https://github.com/pyppeteer/pyppeteer/issues/305

Why 'pytest-timeout' can not stop tests is still a question.

**Comment by AIGeneratedUsername** [comment] 2021-12-10 11:59
# Reproducible code sample (just copy/paste and run)

Do not forget to execute `pip install -U pyppeteer` before running the code.

```python
import logging

import pytest
from pyppeteer import launch

logging.basicConfig(level="DEBUG")
logger = logging.getLogger(__name__)


async def open_browser():
    logger.info("Opening browser...")
    browser = await launch(
        args=["--no-sandbox", "--javascript-harmony"],
    )
    logger.info("Browser opened!")
    return browser


@pytest.mark.timeout(10)
@pytest.mark.asyncio
async def test_open_browser():
    await open_browser()
```

**Comment by andreabisello** [comment] 2022-11-09 11:48
Same issue here.
Sometime i have some tests that hangs and pytest-timeout will never end them.
Not really sure if the problem is the cooperation with xdist.

@AIGeneratedUsername  downgrading to python 3.8 should avoid the problem? i don't really need to use python 3.10

**Comment by skelutten** [comment] 2022-11-21 18:23
Wouldn't a third timeout-method = asyncio be useable?
Starting an asyncio timer that upon expiry will stop the loop and do pytest.fail?
Using a timer similar to this:
https://stackoverflow.com/questions/45419723/python-timer-with-asyncio-coroutine

**Comment by flub** [comment] 2023-10-08 10:35
seems like an asyncio issue, closing as this isn't a report about asyncio though.  If there still is an issue please report it clearly, but even better create a PR as I'm unlikely to work on an asyncio issue myself.

**Closed by flub** 2023-10-08 10:35 UTC

**Comment by AivanF** [comment] 2025-03-06 03:39
I made a simple workaround for async test cases:
https://gist.github.com/AivanF/2001bbcbd70abe76c469c247a8165b44
