### ISSUE TITLE
Allow scaling timeouts via an environment variable

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest-timeout#101] opened 2021-10-08 15:45 UTC
Depending on how beefy your machine is a timeout might suffice on one but fail on another. Would be useful to scale (up) the timeouts set via some env-var.

**Comment by gaborbernat** [comment] 2021-10-10 22:03
If you're referring to the `PYTEST_TIMEOUT`, then there are a few problems with it:

1. Is only used if neither the ``--timeout`` flag or ``timeout`` marker is set.
2. The goal here is not to globally increase the timeout, but rather to scale the already specified timeouts otherwise according to some multipliers. This is to account for OS and machine capability differences. For example, I found that in tox/virtualenv the timeout for a method on Windows is always 2X compared to Linux... Or my local machine is 2X more powerful than the CI, so likely locally I'd like to scale the timeouts set for CI by `0.5`.

**Comment by flub** [comment] 2023-10-08 10:38
As I'm not really a fan of tuning timeouts so small that scaling matters I'm going to close this.  It's not really how it was intended to be used.

**Closed by flub** 2023-10-08 10:38 UTC
